services:
  backend:
    image: sanjaybala18/docker_mern:backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase  
    depends_on:
      - mongodb

  frontend:
    image: sanjaybala18/docker_mern:frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050  

  mongodb:
    image: mongo:latest  # Use the official MongoDB image
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local
